Add Collaborative Text Area example using SharedString
microsoft/FluidExamples pull request #340
Opened 2021-10-27 14:25 UTC by scottn12

This PR adds a new example repo for using the `SharedString` DDS to create a collaborative text area in React.

Uses previously created example: https://github.com/microsoft/FluidFramework/blob/main/experimental/framework/react-inputs/src/CollaborativeTextArea.tsx

2021-11-01 19:43 UTC, heliocliu commented on react-text-area/README.md
> +For a more detailed explanation of this example please click [here](https://fluidframework.com/docs/recipes/shared-string/).
now that this example has been reframed as a text area guide, is it still going to be referenced as a shared string example on the ff site?

2021-11-01 19:52 UTC, heliocliu commented on react-text-area/src/SharedStringHelper.js
> +  insertText(text, pos) {
is this file taken from somewhere else?  if so would it be better to import it instead?

2021-11-01 19:59 UTC, heliocliu commented on shared-string-example/src/CollaborativeTextArea.js
> +    // This is a bad assumption (e.g. performing undo will select the re-added content).
It sounds like the omissions aren't going to be handled here (nor immediately after), so i think it makes sense to keep the comments for anyone who finds it and make sure we have an issue to track updating it later

2021-11-02 13:38 UTC, scottn12 commented on react-text-area/src/SharedStringHelper.js
> +  insertText(text, pos) {
This file was added in Matt's recent changes to the `CollaborativeTextArea` example in the main repo: https://github.com/microsoft/FluidFramework/blob/main/experimental/framework/react-inputs/src/SharedStringHelper.ts

2021-11-02 23:46 UTC, skylerjokiel approved these changes
Looks good. 👍

2021-11-02 23:52 UTC, skylerjokiel requested changes
I totally didn't catch this before but just realized this is javascript and not typescript. 

Can you please port this example to typescript before committing.

2021-11-03 00:59 UTC, heliocliu commented
> I totally didn't catch this before but just realized this is javascript and not typescript.
> 
> Can you please port this example to typescript before committing.

This example is getting the walkthrough tutorial on the website as well, so i think js is right here

2021-11-03 13:01 UTC, scottn12 commented
> I totally didn't catch this before but just realized this is javascript and not typescript.
> 
> Can you please port this example to typescript before committing.

I kept it in javascript since that is the default for `create-react-app`. Should I still port it to ts?

2021-11-03 18:07 UTC, heliocliu submitted a review, later dismissed

2021-11-05 16:42 UTC, scottn12 commented on collaborative-text-area/src/SharedStringHelper.tsx
> +    if (op.type === 0) {
@anthony-murphy I had issues using the `MergeTreeDeltaType` enums and added this workaround for now. Does this seem okay for now?

2021-11-05 16:44 UTC, scottn12 commented on collaborative-text-area/src/App.tsx
> +      }
I noticed some issues with the container not actually being connected on app startup when getting an existing container, so I added this to ensure the container is connected before rendering the UI.

2021-11-05 18:30 UTC, heliocliu commented on collaborative-text-area/src/App.tsx
> +      }
is there a specific scenario where this happens? e.g. only when navigating from a page that had a different instance of the example?

2021-11-05 18:46 UTC, heliocliu commented on collaborative-text-area/src/App.tsx
> +      }
also that this is pretty unintuitive and should probably be fixed separately if it's truly intermittent

2021-11-05 18:46 UTC, heliocliu approved these changes

2021-11-05 18:48 UTC, scottn12 commented on collaborative-text-area/src/App.tsx
> +      }
I find it is actually more common for `container.connected` to `false` than to be `true`. To reproduce I simply will load an instance of the example with an already existing container id.

2021-11-05 19:10 UTC, scottn12 commented on collaborative-text-area/src/App.tsx
> +      }
@heliocliu Do you think I should add a comment to this code block that this should be removed eventually?

2021-11-19 20:58 UTC, heliocliu approved these changes

2021-11-19 21:02 UTC, merged