update fluid framework packets to latest
microsoft/FluidExamples pull request #491
Opened 2022-06-08 19:36 UTC by dannimad

2022-06-08 19:38 UTC, dannimad commented on brainstorm/src/index.tsx
> +    if (container.connectionState !== 2) {
Not entirely sure if this is correct usage. If it is, I will change all other deprecated connected members to connectionState

2022-06-09 17:36 UTC, dannimad commented on brainstorm/src/index.tsx
> +    if (container.connectionState !== 2) {
I can't import ConnectionState, that is why I am using its value.

2022-06-09 17:41 UTC, scottn12 commented on brainstorm/src/index.tsx
> +    if (container.connectionState !== 2) {
We should add `@fluidframework/container-loader` to the dependencies in package.json and import `ConnectionState` here.

2022-06-09 19:49 UTC, scottn12 requested changes

2022-06-09 19:49 UTC, scottn12 commented on angular-demo/package.json
> +    "fluid-framework": "^0.59.4000",
@sonalivdeshpande informed me that 0.59.4000 is unstable and patch 0.59.4001 was released to fix the regressions found in 4000. However, 1.0.0 was also released, so we should just bump to 1.0.0 for the relevant packages

2022-06-13 20:00 UTC, dannimad commented
examples that use azure-client have to use 0.59.3000 version for compatibility issues. Rest of examples up to date to 1.0.0

2022-06-13 23:27 UTC, curtisman commented on brainstorm/package.json
> +    "@fluidframework/container-loader": "^0.59.4001",
should these be consistently update to 1.0.0?

2022-06-13 23:29 UTC, curtisman commented on brainstorm/src/index.tsx
> +    if (container.connectionState !== ConnectionState.Connected) {
Shouldn't this be expose thru fluid-framework as well? @scottn12 I assume that these examples shouldn't import package individually?

2022-06-13 23:29 UTC, dannimad commented on brainstorm/package.json
> +    "@fluidframework/container-loader": "^0.59.4001",
That is what I would think but azure-client package seems outdated. Whenever I tried to update fluid-framework to 1.0.0, azure-client stayed behind and was causing incompatibility issues

2022-06-13 23:30 UTC, curtisman requested changes
:clock1:

2022-06-15 03:59 UTC, skylerjokiel commented on angular-demo/package.json
> +  "version": "1.0.0",
No need to rev the version of these examples.

```suggestion
  "version": "0.1.0",
```

2022-06-15 03:59 UTC, skylerjokiel commented on brainstorm/package.json
> +  "version": "1.0.0",
```suggestion
  "version": "0.1.0",
```

2022-06-15 04:17 UTC, skylerjokiel requested changes

2022-06-15 04:17 UTC, skylerjokiel commented on brainstorm/package.json
> +    "@fluidframework/container-loader": "^0.59.4001",
azure-client is not yet released. These should be on the same version though.

```suggestion
    "@fluidframework/container-loader": "~0.59.3000",
```

2022-06-15 04:17 UTC, skylerjokiel commented on brainstorm/src/index.tsx
> +    if (container.connectionState !== ConnectionState.Connected) {
This was a miss. We don't want azure developers pulling in other packages. @scottn12 I created [Bug 716](https://dev.azure.com/fluidframework/internal/_workitems/edit/716): Re-export ConnectionState from fluid-framework. Let's get this into the next minor release.

In the mean time...

```suggestion
    // TODO: Export ConnectionState type https://github.com/microsoft/FluidFramework/issues/10681
    if (container.connectionState !== 2 /*Connected*/) {
```

2022-06-15 04:17 UTC, skylerjokiel commented on collaborative-text-area/package.json
> +    "@fluidframework/container-loader": "^1.0.0",
don't pull this in.

```suggestion
```

2022-06-15 04:17 UTC, skylerjokiel commented on collaborative-text-area/src/App.tsx
> +      if (container.connectionState !== ConnectionState.Connected) {
```suggestion
      // TODO: Export ConnectionState type https://github.com/microsoft/FluidFramework/issues/10681
      if (container.connectionState !== 2 /*Connected*/) {
```

2022-06-15 04:17 UTC, skylerjokiel commented on multi-framework-diceroller/package.json
> +    "version": "1.0.0",
```suggestion
    "version": "0.1.0",
```

2022-06-15 04:17 UTC, skylerjokiel commented on node-demo/package.json
> +  "version": "1.0.0",
```suggestion
  "version": "0.1.0",
```

2022-06-15 04:17 UTC, skylerjokiel commented on react-demo/package.json
> +  "version": "1.0.0",
```suggestion
  "version": "0.1.0",
```

2022-06-15 04:17 UTC, skylerjokiel commented on react-starter-template/package.json
> +  "version": "1.0.0",
```suggestion
  "version": "0.1.0",
```

2022-06-15 04:17 UTC, skylerjokiel commented on teams-fluid-hello-world/package.json
> +  "version": "1.0.0",
```suggestion
  "version": "0.1.0",
```

2022-06-15 14:46 UTC, curtisman commented on brainstorm/src/index.tsx
> +    if (container.connectionState !== ConnectionState.Connected) {
@skylerjokiel can we add a policy check to make sure we don't accidentally import `inner packages` in these examples?

2022-06-15 14:55 UTC, curtisman commented on brainstorm/src/index.tsx
> +    if (container.connectionState !== ConnectionState.Connected) {
AB#718

2022-06-15 17:23 UTC, dannimad commented on brainstorm/package.json
> +    "@fluidframework/container-loader": "^0.59.4001",
removing container-loader

2022-06-15 18:36 UTC, curtisman approved these changes
:shipit:

2022-06-15 18:43 UTC, merged